site_name: IRMaGE - Neuroimaging tools resources
site_url: https://irmage-tools-resources.readthedocs.io/
nav:
    - Home: index.md
    - 'Tips for users':
      - Resources: users/resources.md
      - Software used by IRMaGe team: users/irmage_soft_list.md
      - DICOM / NIfTI: users/conversionToNifti.md
      - BIDS: users/BIDS.md
      - Quality Control - MRIQC: users/mriqc.md
      - Defacing: users/defacing.md
      - Dwi processing: users/dwi_processing.md
    - 'Tutorials POPULSE MIA':
      - POPULSE: populse_mia_tutorial/populse.md
      - fMRI analysis: populse_mia_tutorial/populse_mia_fMRI.md
    - 'Tips for developers':
      - Code snippets - Python: developers/code-snippets-python.md
      - Deployment of a python project: developers/packaging-python-projects.md
      - Documentation - MKDocs : developers/doc-mkdocs.md 
      - Documentation - Sphinx: developers/doc-sphinx.md  
      - Github: developers/github.md
      - Use virtual environment - example: developers/use-virtual-env-example.md
      - Software installation - Cuda: developers/installation-cuda.md
theme: readthedocs