site_name: Neuroimaging tools resources
site_url: https://populse.github.io/neuroimaging-tools-resources
nav:
    - Home: index.md
    - Users documentation:
      - BIDS: users/BIDS.md
      - mriqc: users/mriqc.md
    - 'Tips for developers':
      - Sphinx documentation: developers/doc-sphinx.md 
      - Code snippets Python: developers/code-snippets-python.md 
      - Github Pull request: developers/github-pullrequest.md
      - Deployment of a python project: developers/packaging-python-projects.md
      - Use virtual environment example: developers/use-virtual-env-example.md
theme: readthedocs